apiVersion: platform.code-code.internal/v1
kind: Provider
metadata:
  name: provider-anthropic
spec:
  provider:
    providerId: provider-anthropic
    displayName: MiniMax
    surfaceId: provider-anthropic
    models:
      - providerModelId: MiniMax-M2.7
        modelRef:
          modelId: MiniMax-M2.7
          vendorId: minimax
      - providerModelId: MiniMax-M2.7-highspeed
        modelRef:
          modelId: MiniMax-M2.7-highspeed
          vendorId: minimax
      - providerModelId: MiniMax-M2.5
        modelRef:
          modelId: MiniMax-M2.5
          vendorId: minimax
      - providerModelId: MiniMax-M2.5-highspeed
        modelRef:
          modelId: MiniMax-M2.5-highspeed
          vendorId: minimax
